### PR TITLE
Bugfix/username validation

### PR DESCRIPTION
**Pull request by prkirby**

### CODE REVIEW

**Comment by selvinortiz** [comment]
This looks great @prkirby, I'll review and merge as soon as I can. Don't worry about the conflicts, they'll be easy to merge.

**Comment by selvinortiz** [comment]
Hey @prkirby, finally had a chance to fully review your PR, sorry for the delay.

There are a couple of things that I'd love for you to tackle before I can merge your changes if you're able to carve out some time.

1. Remove all words in the blacklist that have 4 chars or less.
2. Bring latest changes from dev into your feature branch and resolve any conflicts
3. Before pushing your final changes and creating a new PR, run `yarn run build`

If you are not able to get to these, let me know and I'll add it to my list.

**Comment by prkirby** [comment]
Hey Selvin, Sorry I'm so late on this. Got a new client with a demanding project. Cleared up those user names, and ran npm build. The only conflicts were from the bundle files before I ran build, so there shouldn't be any issues there. Let me know if there is anything else I need to do.

**Comment by selvinortiz** [comment]
@prkirby Awesome, you rock!

**Pull request merged**
